### ISSUE TITLE
Module not found: Can't resolve '@djpfs/react-vlibras'

### ISSUE THREAD

**Issue by maiconsanson** [djpfs/react-vlibras#2]
Estou tentando adicionar o **react-vlibras** em um projeto com NextJs e Javascript.

Quando vou importar o componente, após adicionado o pacote no projeto com Yarn, é retornado um
`Module not found: Can't resolve '@djpfs/react-vlibras'`

```
"dependencies": {
    "@djpfs/react-vlibras": "^1.0.5",
    "@popperjs/core": "^2.10.2",
    "bootstrap": "5.1.1",
    "next": "11.1.2",
    "prop-types": "^15.7.2",
    "react": "17.0.2",
    "react-bootstrap": "^2.0.0-rc.1",
    "react-dom": "17.0.2",
    "styled-components": "^5.3.3"
  },
```

Estou perdendo algo aqui?

**Comment by djpfs** [comment]
Esta usando typescript? Se sim tente executar o ```yarn add @djpfs/react-vlibras-typescript``` no projeto.

**Comment by maiconsanson** [comment]
> Esta usando typescript? Se sim tente executar o `yarn add @djpfs/react-vlibras-typescript` no projeto.

Não é typescript, é javascript mesmo.

**Comment by lucasborgesdev** [comment]
Estou com o mesmo problema e mesmo erro

**Comment by Gabrielpdev** [comment]
Mesmo erro, utilizando NextJS.

Para solucionar, criei um componente da mesma forma que esta nessa lib e deu certo.
Exmplo: 
```
import React, { useEffect } from 'react';

export default function VLibras() {
  useEffect(() => {
    const script = document.createElement('script');
    script.src = 'https://vlibras.gov.br/app/vlibras-plugin.js';
    script.async = true;
    script.onload = (load) => {
      new window.VLibras.Widget('https://vlibras.gov.br/app');
    };
    document.head.appendChild(script);
  }, []);

  return (
    <div vw="true" className="enabled">
      <div vw-access-button="true" className="active" />
      <div vw-plugin-wrapper="true">
        <div className="vw-plugin-top-wrapper" />
      </div>
    </div>
  );
}
```

**Comment by djpfs** [comment]
**Acabei de atualizar o package para a versão 2.0.0 para corrigir esses erros.**

**Por favor atualizem seus packages, a versão para ser usada com typescript foi descontinuada já que consegui gerar os _types_ dessa vez para a versão principal.**

Desinstalem a versão descontinuada, _caso você esteja usando._
`npm uninstall @djpfs/react-vlibras-typescript` ou `yarn remove @djpfs/react-vlibras-typescript`


E instalem a versão mais recente:
`npm i @djpfs/react-vlibras -S` ou `yarn add @djpfs/react-vlibras`
