### ISSUE TITLE
VLibras fora do ar

### ISSUE THREAD

**Issue by ravpacheco** [djpfs/react-vlibras#7]
Olá pessoal, 

os domínios do VLibras estão fora do ar. Consequentemente, o plugin deixou de funcionar.
Estou criando essa issue para estimular a troca de informação sobre incidente.

Alguém sabe de alguma coisa?

**Obs.: O plugin parou de funcionar por volta do dia 9 de dezembro de 2021**

**Comment by djpfs** [comment]
Obrigado por avisar, realmente está fora do ar. Até agora não tenho conhecimento do que ocorreu. 

Update: Nem mesmo o plug-in (oficial) para o Google Chrome funcionou aqui.

**Comment by djpfs** [comment]
Fechando a issue, o site já está no ar novamente e o plugin voltou a funcionar normalmente.
