### ISSUE TITLE
problema ao conectar com o servidor do VLibras

### ISSUE THREAD

**Issue by WelderBM** [djpfs/react-vlibras#8]
Olá, estou tendo esta resposta "Não foi possível estabelecer uma conexão com o serviço de tradução do VLibras" ao clicar em algum texto para traduzir. Não está tirando a funcionalidade, ou seja, traduz normalmente, mas deixa a experiência do usuário ruim...

aparece ao clicar e depois some:
![image](https://user-images.githubusercontent.com/92405076/159559682-793b9d30-9289-49d2-9c75-e9177f83a8a9.png)

Será que estou esquecendo de algo ou é um problema com o VLibras?

**Comment by djpfs** [comment]
Infelizmente o problema esta no próprio VLibras. Eu olhei a documentação deles para ver se algo tinha mudado mas tudo está do mesmo jeito. 

Como esse plugin é só um Wrapper do VLibras, assim que eles resolverem lá resolve aqui.
